// =========== SANDSLIDE — level maps ===========
// Legend:  # wall   (space)/. empty floor   o coin (hand-placed)   P start
//          E exit(sarcophagus)   X mummy (horizontal patrol)   F pufferfish (3x3, puffs)
//          ^ v < > spikes facing up/down/left/right (extend 0.5s after a touch)
//          = laser gate (horizontal beam)   | laser gate (vertical beam)
// Coins: if a map contains any 'o', those are the exact coins; otherwise the game
// auto-places a coin on every slide-swept floor tile (see game.js parse()).
// Hardcoded ASCII per the GDD; parsed by game.js into a grid.

// Level 1 — "CURSED TOMB": editor-authored intro with hand-placed coins.
// Validated: solvable, 0 traps, P grounded, all 66 coins reachable, ~19 swipes.
const CURSED_TOMB = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '###Eooooo####',
  '########o####',
  '########o####',
  '#####oooooo##',
  '#####o##o.o##',
  '#####o##ooo##',
  '#####ooo#####',
  '#ooooo#o#####',
  '#o###ooo#####',
  '#o###########',
  '#o###oooooo##',
  '#ooooo####o##',
  '####oo##ooo##',
  '####oo##o####',
  '####oo##oooo#',
  '###########o#',
  '#######...#o#',
  '#######.Pooo#',
  '#############',
];

// Level 2 — "lvl_2" (editor-authored). Validated: solvable, 0 traps, P grounded,
// all 71 coins reachable, ~22 swipes.
const LVL_2 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######E######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '########oooo#',
  '###########o#',
  '########Pooo#',
  '#############',
];

// Level 3 — "lvl_3" (editor-authored): a patrolling mummy (X), timed passage.
// Validated: solvable, 0 traps, P grounded, all 65 coins reachable, ~14 swipes.
const LVL_3 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '##E##########',
  '##.##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooooo#####',
  '###o...o#####',
  '###o...o#####',
  '###o..Xo#####',
  '###ooooo#####',
  '###o#########',
  '###oooooo####',
  '########o####',
  '###oooo#o####',
  '###o..o#o####',
  '###o##...####',
  '###o##..o####',
  '###o#########',
  '#ooooooooooo#',
  '#o#o#######o#',
  '#o#o###...#o#',
  '#ooo###.Pooo#',
  '#############',
];

// Level 4 — "lvl_4" (editor-authored). Validated: solvable, 0 traps, P grounded,
// all 76 coins reachable, ~28 swipes.
const LVL_4 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######ooo####',
  '######o#E####',
  '######o######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '####...#oooo#',
  '#..#.#.####o#',
  '#P...#...ooo#',
  '#############',
];

// Level 5 — "lvl_5" (editor-authored, directional spikes). Inserted as-is per
// request; solvability checked by the author in-game.
const LVL_5 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######ooo####',
  '######o#E####',
  '######o######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##>ooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####ooo<#',
  '#ooo####o####',
  '####ooo#oooo#',
  '#..#o#o####o#',
  '#P.oo#oooooo#',
  '#############',
];

export const LEVELS = [
  { name: 'CURSED TOMB', map: CURSED_TOMB },
  { name: 'lvl_2',       map: LVL_2 },
  { name: 'lvl_3',       map: LVL_3 },
  { name: 'lvl_4',       map: LVL_4 },
  { name: 'lvl_5',       map: LVL_5 },
];
