// =========== SANDSLIDE — level maps ===========
// Legend:  # wall   (space)/. empty floor   o coin (hand-placed)   P start
//          E exit(sarcophagus)   X mummy (horizontal patrol)   ^ spikes
//          = laser gate (horizontal beam)   | laser gate (vertical beam)
// Coins: if a map contains any 'o', those are the exact coins; otherwise the game
// auto-places a coin on every slide-swept floor tile (see game.js parse()).
// Hardcoded ASCII per the GDD; parsed by game.js into a grid.

// Level 1 — "CURSED TOMB": editor-authored intro with hand-placed coins.
// Validated: solvable, 0 traps, P grounded, all 66 coins reachable, ~19 swipes.
const CURSED_TOMB = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '###Eooooo####',
  '########o####',
  '########o####',
  '#####oooooo##',
  '#####o##o.o##',
  '#####o##ooo##',
  '#####ooo#####',
  '#ooooo#o#####',
  '#o###ooo#####',
  '#o###########',
  '#o###oooooo##',
  '#ooooo####o##',
  '####oo##ooo##',
  '####oo##o####',
  '####oo##oooo#',
  '###########o#',
  '#######...#o#',
  '#######.Pooo#',
  '#############',
];

// Hand-authored in the editor: a long winding labyrinth with hand-placed coins.
// Validated: solvable, 0 traps, P grounded, all 128 coins reachable, ~36 swipes.
const HOLLOW_LABYRINTH = [
  '#############',
  '#E#ooooooooo#',
  '#o#o#######o#',
  '#o#o#######o#',
  '#ooo######oo#',
  '#oo#######o##',
  '##########o##',
  '##########o##',
  '#oooooooooo##',
  '#o###########',
  '#ooooo#######',
  '#####ooooo###',
  '#########o###',
  '######oooo###',
  '######o#oo###',
  '######o#oo###',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '########oooo#',
  '###########o#',
  '########Pooo#',
  '#############',
];

// Editor-authored trap chamber: a patrolling mummy (X) + a vertical laser gate (|).
// Validated: solvable, 0 traps, P grounded, all 69 coins reachable, ~14 swipes.
// Note: the mummy must be TIMED (not walked around) — that's intended here.
const TRAPPED_TOMB = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '##E##########',
  '##.##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooooo#####',
  '###o...o#####',
  '###o...o#####',
  '###o..Xo#####',
  '###ooooo#####',
  '###o#########',
  '###oooooo####',
  '########o####',
  '###oooo#o####',
  '###o.|o#o####',
  '###o##o#o####',
  '###o##ooo####',
  '###o#########',
  '#ooooooooooo#',
  '#o#o#######o#',
  '#o#o###...#o#',
  '#ooo###.Pooo#',
  '#############',
];

export const LEVELS = [
  { name: 'CURSED TOMB',      map: CURSED_TOMB },
  { name: 'HOLLOW LABYRINTH', map: HOLLOW_LABYRINTH },
  { name: 'TRAPPED TOMB',     map: TRAPPED_TOMB },
];
