// =========== SANDSLIDE — level maps ===========
// Legend:  # wall   (space)/. empty floor   o coin (hand-placed)   * star pickup   P start
//          E exit(sarcophagus)   X mummy (horizontal patrol)   F pufferfish (3x3, puffs)
//          ^ v < > spikes facing up/down/left/right (extend 0.5s after a touch)
//          = laser gate (horizontal beam)   | laser gate (vertical beam)
// Coins: if a map contains any 'o', those are the exact coins; otherwise the game
// auto-places a coin on every slide-swept floor tile (see game.js parse()).
// Stars ('*'): hand-placed rating pickups — the level result shows how many of
// them (0..3) the player grabbed. Walkable like coins, never auto-coined.
// Hardcoded ASCII per the GDD; parsed by game.js into a grid.

// Level 1 — "CURSED TOMB": editor-authored intro with hand-placed coins.
// Validated: solvable, 0 traps, P grounded, all 66 coins reachable, ~19 swipes.
const CURSED_TOMB = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '###Eooooo####',
  '########o####',
  '########o####',
  '#####oooooo##',
  '#####o##o.o##',
  '#####o##ooo##',
  '#####ooo#####',
  '#ooooo#o#####',
  '#o###ooo#####',
  '#o###########',
  '#o###oooooo##',
  '#ooooo####o##',
  '####oo##ooo##',
  '####oo##o####',
  '####oo##oooo#',
  '###########o#',
  '#######...#o#',
  '#######.Pooo#',
  '#############',
];

// Level 2 — "lvl_2" (editor-authored). Validated: solvable, 0 traps, P grounded,
// all 71 coins reachable, ~22 swipes.
const LVL_2 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######E######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '########oooo#',
  '###########o#',
  '########Pooo#',
  '#############',
];

// Level 3 — "lvl_3" (editor-authored): a patrolling mummy (X), timed passage.
// 69 coins; solvability author-verified in-game.
const LVL_3 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '##E##########',
  '##.##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooooo#####',
  '###o...o#####',
  '###o...o#####',
  '###o..Xo#####',
  '###ooooo#####',
  '###o#########',
  '###oooooo####',
  '########o####',
  '###oooo#o####',
  '###o..o#o####',
  '###o##o.o####',
  '###o##ooo####',
  '###o#########',
  '#ooooooooooo#',
  '#o#o#######o#',
  '#o#o###...#o#',
  '#ooo###.Pooo#',
  '#############',
];

// Level 4 — "lvl_4" (editor-authored): adds a laser gate (=). 86 coins;
// solvability author-verified in-game.
const LVL_4 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######ooo####',
  '######o#E####',
  '######o######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####ooo#####',
  '#######o#####',
  '###oooo=#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '####ooo#oooo#',
  '#..#o#o####o#',
  '#P.oo#oooooo#',
  '#############',
];

// Level 5 — "lvl_5" (editor-authored, directional spikes). Inserted as-is per
// request; solvability checked by the author in-game.
const LVL_5 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '######ooo####',
  '######o#E####',
  '######o######',
  '######o######',
  '######oooooo#',
  '###########o#',
  '###########o#',
  '###########o#',
  '##oooooooooo#',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##>ooo#######',
  '#####.oo#####',
  '#######o#####',
  '###ooooo#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####ooo<#',
  '#ooo####o####',
  '####ooo#oooo#',
  '#..#o#o####o#',
  '#P.oo#oooooo#',
  '#############',
];

// Level 6 — "lvl_6" (editor-authored): looping top room + a pufferfish (F).
// 3 star pickups; solvability author-verified in-game.
const LVL_6 = [
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '#############',
  '###oooooooo##',
  '###o######o##',
  '###ooooo##o##',
  '#######oE#o##',
  '##########o##',
  '##oooooooo*##',
  '##o##########',
  '##o##########',
  '##o##########',
  '##o##########',
  '##oooo#######',
  '#####ooo#####',
  '#####oFo#####',
  '###oooo*#####',
  '#ooo#########',
  '#o###########',
  '#o#ooooooooo#',
  '#o#o######.o#',
  '#o#o####oooo#',
  '#ooo####o####',
  '####ooo#*ooo#',
  '#..#o#o####o#',
  '#P.oo#oooooo#',
  '#############',
];

export const LEVELS = [
  { name: 'CURSED TOMB', map: CURSED_TOMB },
  { name: 'lvl_2',       map: LVL_2 },
  { name: 'lvl_3',       map: LVL_3 },
  { name: 'lvl_4',       map: LVL_4 },
  { name: 'lvl_5',       map: LVL_5 },
  { name: 'lvl_6',       map: LVL_6 },
];
